/**
 * The default trigger handler implement ITrigger interface.
 *
 * @author  Matt Yuan
 * @created 4/20/2015
 * @version 1.0
 * @since   33.0
 *
 * @changelog
 * 4/20/2015 Matt Yuan - Created.
 */

public virtual class TriggerHandler implements ITrigger 
{
    public virtual void beforeInsert() 
    { 
    
    }

    public virtual void beforeUpdate() 
    { 
    
    }

    public virtual void beforeDelete() 
    { 
    
    }

    public virtual void afterInsert() 
    { 
    
    }

    public virtual void afterUpdate() 
    { 
    
    }

    public virtual void afterDelete() 
    { 
    
    }

    public virtual void afterUndelete() 
    { 
    
    }
}